# Generated by Django 2.2.10 on 2021-03-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_answer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TEXT', 'text'), ('CHOICE', 'choice'), ('MULTI_CHOICE', 'multi_choice')], default=(('TEXT', 'text'), ('CHOICE', 'choice'), ('MULTI_CHOICE', 'multi_choice')), max_length=12),
        ),
    ]
